### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by pqn** [bdwyertech/go-scutil#1]
I noticed this was a dependency of [bdwyertech/go-get-proxied](https://github.com/bdwyertech/go-get-proxied), which seems like the most up-to-date fork of [rapid7/go-get-proxied](https://github.com/rapid7/go-get-proxied). Would you be open to adding a permissive license to this repo? Would love to use this.

**Comment by bdwyertech** [comment]
Sure, sounds like you're more knowledgeable than I in this regard.  Typically I just pick MIT.  Any suggestions?  Open to a merge request.

**Comment by pqn** [comment]
MIT works great, I made a PR for your convenience: https://github.com/bdwyertech/go-scutil/pull/2

**Comment by bdwyertech** [comment]
Thanks!
